import type { Service } from './types';

export const sampleService: Service = {
  name: 'HR Services',
  domain: 'People & Workplace',
  subServices: [
    {
      id: 'onboarding',
      name: 'Employee Onboarding Request',
      requestType: 'Sub-service',
      entitlement: 'All DEWA Users',
      entitlementNote: 'Self + on behalf of',
      approvals: ['Direct Manager', 'HR Head'],
      fulfillmentType: 'Work Order',
      fulfillmentCode: 'WO',
      supportGroup: 'HR-Ops',
      supportNote: 'L2 · 24×5',
      sla: { label: '3 working days', risk: 'timed' },
    },
    {
      id: 'offboarding',
      name: 'Employee Offboarding',
      requestType: 'Sub-service',
      entitlement: 'All DEWA Users',
      entitlementNote: 'Manager initiated',
      approvals: ['Direct Manager', 'IT Security'],
      fulfillmentType: 'Work Order',
      fulfillmentCode: 'WO',
      supportGroup: 'HR-Ops',
      supportNote: 'L2 · 24×5',
      sla: { label: '2 working days', risk: 'timed' },
    },
    {
      id: 'salary-certificate',
      name: 'Salary Certificate',
      requestType: 'Sub-service',
      entitlement: 'DEWA Employees',
      approvals: ['Direct Manager'],
      fulfillmentType: 'Service Request',
      fulfillmentCode: 'SR',
      supportGroup: 'HR-Shared-Services',
      supportNote: 'L1 · 8×5',
      sla: { label: '1 working day', risk: 'timed' },
    },
    {
      id: 'business-travel',
      name: 'Business Travel Request',
      requestType: 'Sub-service',
      entitlement: 'DEWA Employees',
      entitlementNote: 'Grade 8+',
      approvals: ['Direct Manager', 'Finance', 'HR Head'],
      fulfillmentType: 'Work Order',
      fulfillmentCode: 'WO',
      supportGroup: 'HR-Travel-Desk',
      supportNote: 'L2 · 8×5',
      sla: { label: '5 working days', risk: 'timed' },
    },
    {
      id: 'policy-inquiry',
      name: 'HR Policy Inquiry',
      requestType: 'Sub-service',
      entitlement: 'All DEWA Users',
      approvals: [],
      fulfillmentType: 'Service Request',
      fulfillmentCode: 'SR',
      supportGroup: 'HR-Helpdesk',
      supportNote: 'L1 · 8×5',
      sla: { label: 'No SLA defined', risk: 'none' },
    },
  ],
};

export const sampleItService: Service = {
  name: 'IT End-User Services',
  domain: 'Technology Operations',
  subServices: [
    {
      id: 'laptop-request',
      name: 'Laptop Request',
      requestType: 'Sub-service',
      entitlement: 'All DEWA Users',
      entitlementNote: 'Manager on behalf of',
      approvals: ['Direct Manager', 'IT Asset Owner'],
      fulfillmentType: 'Work Order',
      fulfillmentCode: 'WO',
      supportGroup: 'IT-Enduser-Support',
      supportNote: 'L2 · 24×7',
      sla: { label: '4 working days', risk: 'timed' },
    },
    {
      id: 'password-reset',
      name: 'Password Reset',
      requestType: 'Sub-service',
      entitlement: 'All DEWA Users',
      approvals: [],
      fulfillmentType: 'Service Request',
      fulfillmentCode: 'SR',
      supportGroup: 'IT-Service-Desk',
      supportNote: 'L1 · 24×7',
      sla: { label: '4 hours', risk: 'timed' },
    },
    {
      id: 'software-install',
      name: 'Software Installation',
      requestType: 'Sub-service',
      entitlement: 'DEWA Employees',
      entitlementNote: 'Licensed catalogue only',
      approvals: ['Direct Manager', 'IT Security', 'Licence Manager'],
      fulfillmentType: 'Work Order',
      fulfillmentCode: 'WO',
      supportGroup: 'IT-Enduser-Support',
      supportNote: 'L2 · 8×5',
      sla: { label: '2 working days', risk: 'timed' },
    },
    {
      id: 'vpn-access',
      name: 'Remote VPN Access',
      requestType: 'Sub-service',
      entitlement: 'DEWA Employees',
      entitlementNote: 'Grade 6+',
      approvals: ['Direct Manager', 'IT Security'],
      fulfillmentType: 'Service Request',
      fulfillmentCode: 'SR',
      supportGroup: 'IT-Network-Ops',
      supportNote: 'L3 · 24×7',
      sla: { label: 'No SLA defined', risk: 'none' },
    },
  ],
};

export const sampleServices: Service[] = [sampleService, sampleItService];
